<script lang="ts">
import Form from '$lib/components/Form.svelte';
import { getFormFields } from '$lib/helpers/wrappers';
import { modal } from '$lib/stores/store';
	// import type { PageData } from '.svelte-kit/types/src/routes/prisoners/$types';
import Modal, {bind} from 'svelte-simple-modal';

$modal = null;

const add_prisoner = async () => {
    // the form fields are generated by passing the Collection name and path to trigger the POST request
    // const formFields = await getFormFields('Add Prisoner', 'prisoners');
    const formFields = await getFormFields('Test 22', 'prisoners');

    console.log('Field retrieved: ', formFields);

    modal.set(
        bind(
            Form, 
            {
                formTitle: 'Add Prisoner',
                formDescription: 'All fields are required',
                formSubmitAction: 'addPrisoner',
                formFields: formFields
            }
        )
    )
}
</script>

<div class="container mx-auto pt-6">
    <Modal show={$modal}>
        <button class="rounded-full bg-sky-500 text-white px-4 py-1" on:click={add_prisoner}>Add Inmate</button>
    </Modal>
</div>


